USE [web-api.online]
GO
INSERT [dbo].[AspNetUsers] ([Id], [UserName], [NormalizedUserName], [Email], [NormalizedEmail], [EmailConfirmed], [PasswordHash], [SecurityStamp], [ConcurrencyStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEnd], [LockoutEnabled], [AccessFailedCount]) VALUES (N'0996e6bb-ea74-447b-9832-d1b5a02d4a70', N'BinanceBotParserAccount', N'BINANCEBOTPARSERACCOUNT', N'BinanceBot@account.com', N'BINANCEBOT@ACCOUNT.COM', 0, N'AQAAAAEAACcQAAAAEICThOTkYjSjK5jyZevrxyXQKFJSkKBLBJtyFFsBOWtXdaSzavQAWyuoQOjzcI60Rw==', N'WSU5WODB2ZPLFWJTVUMLEFGLXC2HIQL7', N'af9397e0-6e95-4146-acc6-dfaa54609e5d', NULL, 0, 0, NULL, 1, 0)
GO
INSERT [dbo].[AspNetUsers] ([Id], [UserName], [NormalizedUserName], [Email], [NormalizedEmail], [EmailConfirmed], [PasswordHash], [SecurityStamp], [ConcurrencyStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEnd], [LockoutEnabled], [AccessFailedCount]) VALUES (N'1d6254fc-8f94-4229-b09f-a2b225c128b0', N'BitFinexBotParserAccount', N'BITFINEXBOTPARSERACCOUNT', N'BitFinexBot@account.com', N'BITFINEXBOT@ACCOUNT.COM', 0, N'AQAAAAEAACcQAAAAEIaLsIvppF8t/wKD9bGJUSKJoVZY04K3/s6RdW+p8OGzJRVAaHYxM5mbw63L2bXDvg==', N'E3X2AVHCLBZCUJNWXIS6IDURXK3VAKVN', N'3c6a161c-6edd-497e-ba09-4406d09f06f1', NULL, 0, 0, NULL, 1, 0)
GO
INSERT [dbo].[AspNetUsers] ([Id], [UserName], [NormalizedUserName], [Email], [NormalizedEmail], [EmailConfirmed], [PasswordHash], [SecurityStamp], [ConcurrencyStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEnd], [LockoutEnabled], [AccessFailedCount]) VALUES (N'40ffde92-878c-4c09-ac6b-c86a769d1623', N'alex.pigalyov@gmail.com', N'ALEX.PIGALYOV@GMAIL.COM', N'alex.pigalyov@gmail.com', N'ALEX.PIGALYOV@GMAIL.COM', 0, N'AQAAAAEAACcQAAAAEMGh3KyRXbNgFE8Xv/XmdT3ViCOi4X2WVCRiA7nIqaXrHUbE+URvo7Sb0biYTdQZsA==', N'7DSMMORLJEQSVUFYDLMO7XABIXNRAXVD', N'8f7ff654-4437-4fbc-aa90-b6723711c176', NULL, 0, 0, NULL, 1, 0)
GO
INSERT [dbo].[AspNetUsers] ([Id], [UserName], [NormalizedUserName], [Email], [NormalizedEmail], [EmailConfirmed], [PasswordHash], [SecurityStamp], [ConcurrencyStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEnd], [LockoutEnabled], [AccessFailedCount]) VALUES (N'73e1341c-f193-45cb-ac0b-4dfedc605a0d', N'mathewsun@rambler.ru', N'MATHEWSUN@RAMBLER.RU', N'mathewsun@rambler.ru', N'MATHEWSUN@RAMBLER.RU', 0, N'AQAAAAEAACcQAAAAEA2pkFAiJ6Jy2fzpCXsaSWuOQwW8yAoKfOvCBht90WyJVgHNXTEOjDXOiIJNECXVpw==', N'OFPJS5WCP3WFQ2YMVDDOUL6HC2CYLKAB', N'6163a952-35b7-43c7-a97b-314fa5699246', NULL, 0, 0, NULL, 1, 0)
GO
INSERT [dbo].[AspNetUsers] ([Id], [UserName], [NormalizedUserName], [Email], [NormalizedEmail], [EmailConfirmed], [PasswordHash], [SecurityStamp], [ConcurrencyStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEnd], [LockoutEnabled], [AccessFailedCount]) VALUES (N'824bef62-0f83-4e98-bec1-85ddca883324', N'PoloniexBotParserAccount', N'POLONIEXBOTPARSERACCOUNT', N'PoloniexBot@account.com', N'POLONIEXBOT@ACCOUNT.COM', 0, N'AQAAAAEAACcQAAAAED0uuFHIkuPsCrbavHvdv2f7PjiNHLj1Krq48MxYQDwhQbeq7L8I7KihdevQXuP/sQ==', N'SA6KGZCGKHC3T3EVHYPXWQF2NXCL6LIJ', N'5981b82d-15da-4811-a9d6-95c9a21e4f9e', NULL, 0, 0, NULL, 1, 0)
GO
INSERT [dbo].[AspNetUsers] ([Id], [UserName], [NormalizedUserName], [Email], [NormalizedEmail], [EmailConfirmed], [PasswordHash], [SecurityStamp], [ConcurrencyStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEnd], [LockoutEnabled], [AccessFailedCount]) VALUES (N'cce4bbb8-e74c-4d2b-af4c-b87da455c6cf', N'KucoinBotParserAccount', N'KUCOINBOTPARSERACCOUNT', N'KucoinBot@account.com', N'KUCOINBOT@ACCOUNT.COM', 0, N'AQAAAAEAACcQAAAAEObRZQLROLv4FtSA+SROwixJa01gAhf5tlgwR2yl2KFNTbd2bZnPt2xnDKh8JAJpBA==', N'SSWHTLMOGLTVDAWOYDATGA6ZVTIARITT', N'addd6a13-bb90-441d-821e-889a03614113', NULL, 0, 0, NULL, 1, 0)
GO
INSERT [dbo].[AspNetUsers] ([Id], [UserName], [NormalizedUserName], [Email], [NormalizedEmail], [EmailConfirmed], [PasswordHash], [SecurityStamp], [ConcurrencyStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEnd], [LockoutEnabled], [AccessFailedCount]) VALUES (N'f15ad39c-2e1d-492b-b3af-047fad496645', N'mathewsun@yandex.ru', N'MATHEWSUN@YANDEX.RU', N'mathewsun@yandex.ru', N'MATHEWSUN@YANDEX.RU', 0, N'AQAAAAEAACcQAAAAEMPUt3KyFehwjy1jMHZoDb7WhipReiu3wmudRusN2HJHtIM21y17Ox4FIZcpwZrpbQ==', N'TN3P74GZPZS7HBVQ62WK2NGCTBX4CBN4', N'c219af2d-ee55-4d3d-ba38-e3d8ccb5703d', NULL, 0, 0, NULL, 1, 0)
GO
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'00000000000000_CreateIdentitySchema', N'5.0.4')
GO
